apiVersion: v1
kind: Service
metadata:
  name: reading-list-api
  namespace: default
spec:
  selector:
    app: reading-list-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
